⚠️ CONFLICT! Lineage pull request for: skeleton
cisagov/pca-gophish-composition pull request #22
Opened 2020-11-18 21:20 UTC by cisagovbot

# Lineage Pull Request: CONFLICT #

<img align="left" width="100" src="https://raw.githubusercontent.com/cisagov/action-lineage/develop/src/achtung.gif">

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-python-library.git`](https://github.com/cisagov/skeleton-python-library.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

The `lineage/skeleton` branch has **one or more unresolved merge conflicts**
that you must resolve before merging this pull request!

## How to resolve the conflicts ##

1. Take ownership of this pull request by removing any other assignees.

1. Clone the repository locally, and reapply the merge:

    ```console
    git clone git@github.com:cisagov/pca-gophish-composition.git pca-gophish-composition
    cd pca-gophish-composition
    git remote add skeleton https://github.com/cisagov/skeleton-python-library.git
    git remote set-url --push skeleton no_push
    git switch develop
    git checkout -b lineage/skeleton --track origin/develop
    git pull skeleton HEAD
    git status
    ```

1. Review the changes displayed by the `status` command.  Fix any conflicts and
   possibly incorrect auto-merges.

1. After resolving each of the conflicts, `add` your changes to the
   branch, `commit`, and `push` your changes:

    ```console
    git add .github/CODEOWNERS .pre-commit-config.yaml setup.py src/example/__init__.py 
    git commit
    git push --force --set-upstream origin lineage/skeleton
    ```

    Note that you may _append_ to the default merge commit message
    that git creates for you, but *please do not delete the existing
    content*.  It provides useful information about the merge that is
    being performed.

1. Wait for all the automated tests to pass.

1. Check the "Everything is cool" checkbox below:

    - [ ] ✌️ The conflicts in this pull request have been resolved.

1. Mark this draft pull request "Ready for review".

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

2020-11-19 21:26 UTC, jsf9k requested changes
I think there are some unnecessary quotes here.  Not sure if they should be fixed here or upstream.

2020-11-19 21:26 UTC, jsf9k commented on .github/workflows/build.yml
> +            py${{ matrix.python-version }}-\
I don't think these quotes are necessary.

2020-11-19 21:26 UTC, jsf9k commented on .github/workflows/build.yml
> +            py${{ matrix.python-version }}-\
Quotes again

2020-11-19 21:41 UTC, mcdonnnj commented on .github/workflows/build.yml
> +            py${{ matrix.python-version }}-\
The quotes are needed cleanly turn it into a single string.

Pulled from [cisagov/skeleton-generic](https://github.com/cisagov/skeleton-generic) GHA runs:

```console
key: lint-Linux-py3.9.0-4d6c2ba2786097c74dca7abc3707d576242350073cf738b69537399d20cd487c-c2a90360b9139caea83bba3d7e2739e350b7e3aa53efe7922108b2b44325c3ee-9ff6996b601c7d804757a92c10ff7756d543bded97848e5705c3034c17535606
```

vs

```console
key: lint-Linux-\ py3.9.0-\ 4d6c2ba2786097c74dca7abc3707d576242350073cf738b69537399d20cd487c-\ c2a90360b9139caea83bba3d7e2739e350b7e3aa53efe7922108b2b44325c3ee-\ ac3b46e98deceeb8fd1f101d93a2b45598b68a7975471a0d63d052e0b2f20ca8
```

2020-11-19 21:42 UTC, mcdonnnj commented on .github/workflows/build.yml
> +            py${{ matrix.python-version }}-\
Adding on, when changed to a block scalar it comes out as:

```console
key: lint-Linux-\
  py3.9.0-\
  4d6c2ba2786097c74dca7abc3707d576242350073cf738b69537399d20cd487c-\
  c2a90360b9139caea83bba3d7e2739e350b7e3aa53efe7922108b2b44325c3ee-\
  ac3b46e98deceeb8fd1f101d93a2b45598b68a7975471a0d63d052e0b2f20ca8"
```

So we may want to codify on using quotation marks honestly.

2020-11-20 15:47 UTC, jsf9k commented on .github/workflows/build.yml
> +            py${{ matrix.python-version }}-\
OK.  At a minimum I can defer this discussion since it's an upstream decision.

2020-11-20 15:47 UTC, jsf9k approved these changes

2020-11-22 21:37 UTC, mcdonnnj requested changes
🤖 but with a requested change.

2020-11-22 21:37 UTC, mcdonnnj commented on setup.py
> +    install_requires=["docopt", "gophish", "schema", "setuptools >= 24.2.0"],
The `schema` package is not used in this repository, so it should not be added to `install_requires`.

2020-11-23 15:38 UTC, jsf9k commented on setup.py
> +    install_requires=["docopt", "gophish", "schema", "setuptools >= 24.2.0"],
Eagle eyes!  Removed in commit 8381a17.

2020-11-23 16:01 UTC, mcdonnnj approved these changes
🌟

2020-11-23 16:01 UTC, mcdonnnj commented on setup.py
> +    install_requires=["docopt", "gophish", "schema", "setuptools >= 24.2.0"],
Thanks!

2020-11-23 16:35 UTC, hillaryj approved these changes
🌮

2020-11-23 17:59 UTC, merged