Update to use latest gophish
cisagov/pca-gophish-composition pull request #28
Opened 2021-04-02 20:00 UTC by JCantu248

## 🗣 Description ##

Updated `docker-compose.yml` to pull latest `cisagov/gophish`

## 💭 Motivation and context ##

Previous version was hardcoded to `0.7.1`, this change moves it to `cisagov/gophish:latest`. At this time, the latest version is `0.11`, so we were a little out of date. 

## 🧪 Review Guidance ##

Navigate to the `pca-gophish-composition` directory and run the `docker-compose up` command. 

Once the service is running, navigate to the address and login with the `admin` credentials outlined in the updated `README`. 

Under Account Settings, verify that the current version is `0.11.0`

2021-04-03 14:56 UTC, dav3r requested changes
Hopefully you have also set up your Dev environment according to [CONTRIBUTING.md](https://github.com/cisagov/pca-gophish-composition/blob/develop/CONTRIBUTING.md).  If you did, then you should be able to easily do both of the following steps (which should be done for every release of this repo):
* Update the version of this project using the [`bump_version.sh`](https://github.com/cisagov/pca-gophish-composition/blob/develop/bump_version.sh) script:
```console
./bump_version.sh minor
```
* Tag this release:
```console
./tag.sh
```

If you have trouble getting either of those scripts to run or have any questions about what I'm asking for here, please let me know.

2021-04-03 14:56 UTC, dav3r commented on docker-compose.yml
> +    image: cisagov/gophish:latest
Our standard is to pin a specific version of the Docker images (rather than `latest`) we use in our compositions.  This forces us to be very deliberate whenever we want to modify the image versions that we use.  It also means that we know exactly which version of an image was used in a particular version of a composition.

With that said, I noticed that `cisagov/gophish:latest` had been pointing to an image that was from August 2020.  So I created an up-to-date version of the image (using the code included in https://github.com/cisagov/gophish/pull/1) and pushed it to Docker Hub tagged it as [`cisagov/gophish:0.11.1`](https://hub.docker.com/layers/cisagov/gophish/0.11.1/images/sha256-4a02606ff7f543fc2a5d41c232894351a8ef1021405ffa6b70828ffd545d8898?context=repo) (and also [`cisagov/gophish:latest`](https://hub.docker.com/layers/cisagov/gophish/latest/images/sha256-4a02606ff7f543fc2a5d41c232894351a8ef1021405ffa6b70828ffd545d8898?context=repo)).

@JCantu248 - Please update this PR to use [`cisagov/gophish:0.11.1`](https://hub.docker.com/layers/cisagov/gophish/0.11.1/images/sha256-4a02606ff7f543fc2a5d41c232894351a8ef1021405ffa6b70828ffd545d8898?context=repo) instead of `latest`.

2021-04-03 18:58 UTC, jsf9k reviewed
Looks good, but please make the change that @dav3r requested.  After that I'm happy to approve.

2021-04-06 03:28 UTC, dav3r commented on docker-compose.yml
> +    image: cisagov/gophish:latest
@JCantu248 - After the changes in https://github.com/cisagov/gophish/pull/2 and https://github.com/cisagov/gophish-docker/pull/24, you should now use the newly-created [`cisagov/gophish:0.11.0-cisa.1`](https://hub.docker.com/layers/cisagov/gophish/0.11.0-cisa.1/images/sha256-0024eb0ab88963e25bcb723c3c700341cb82c4992536e8f3eeb9b93877fc5478?context=repo) in the Docker compose file in this PR.

2021-04-06 11:36 UTC, dav3r commented on docker-compose.yml
> +    image: cisagov/gophish:latest
```suggestion
    # Reminder: cisagov/gophish Docker images are created with
    # cisagov/gophish-docker, not cisagov/gophish!
    image: cisagov/gophish:0.11.0-cisa.1
```

2021-04-06 17:23 UTC, dav3r approved these changes
Looks good to me - thanks @JCantu248! 🚀

2021-04-06 17:30 UTC, dav3r commented on docker-compose.yml
> +    image: cisagov/gophish:latest
Taken care of with https://github.com/cisagov/pca-gophish-composition/pull/28/commits/9189a5fd63b8ce8740fb720fa2b4aecca107f1bb. 👍

2021-04-06 17:35 UTC, jsf9k approved these changes
Strong work!

2021-04-06 17:35 UTC, jsf9k commented on src/gophish_init/_version.py
> +__version__ = "0.1.0"
You probably only needed to bump the patch version here, but I'll let it slide this time.

2021-04-06 17:36 UTC, felddy approved these changes
Strong work.  💪 
🎣

2021-04-06 17:36 UTC, dav3r commented on src/gophish_init/_version.py
> +__version__ = "0.1.0"
I needed a win here!! 🙃

2021-04-06 17:37 UTC, felddy commented on src/gophish_init/_version.py
> +__version__ = "0.1.0"
https://semver.org/#spec-item-7

2021-04-06 18:02 UTC, merged