Pcadev 94 create live pca script
cisagov/pca-gophish-composition pull request #32
Opened 2021-07-13 20:42 UTC by nickviola

#  #

## 🗣 Description ##

## 💭 Motivation and context ##

## 🧪 Testing ##

## 📷 Screenshots (if appropriate) ##

## ✅ Checklist ##

* [ ] This PR has an informative and human-readable title.
* [ ] Changes are limited to a single goal - _eschew scope creep!_
* [ ] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
* [ ] All relevant type-of-change labels have been added.
* [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
* [ ] Tests have been added and/or modified to cover the changes in this PR.
* [ ] All new and existing tests pass.

2021-09-22 14:25 UTC, nickviola commented
ToDo Items and ideas are being captured and planned in the following Project https://github.com/orgs/cisagov/projects/12.

2021-09-28 19:53 UTC, nickviola commented
Just dropping a note here to confirm that this one is ready for review when someone gets a chance to take a look at it. I know it sat in draft status for awhile, so just wanted to confirm that it's ready for feedback now. Thanks in advance!

2021-10-08 19:10 UTC, dav3r requested changes
I requested a bunch of small changes, but nothing that should be particularly difficult to clean up.

2021-10-08 19:10 UTC, dav3r commented on .pre-commit-config.yaml
> +    rev: v5.0.8
This version change should not be done in this PR.  When we update our skeletons (see https://github.com/cisagov/skeleton-generic/pull/93), the `ansible-lint` version will get updated via a lineage PR.

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +# in GoPhish by orchestrating the flow of the capabilities derived from
We should use the same capitalization as [the developer uses](https://getgophish.com/blog/):
```suggestion
# in Gophish by orchestrating the flow of the capabilities derived from
```

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +# interaction was reqneed by the user to create template/import files and move
Typo:
```suggestion
# interaction was required by the user to create template/import files and move
```

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +# and simplifying the flow of the gophish campaign interaction process.#
Fix capitalization, make verb tense agree, and remove unnecessary `#`:
```suggestion
# the need to remember various Docker run commands for various images/scripts
# and simplifies the flow of the Gophish campaign interaction process.
```

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +#   Li-PCA Script Script
I think this is what you meant here?
```suggestion
#   Li-PCA Setup Script
```

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +# OVERRIDE DEFAULT VALUES WITH ENV VARS AS NEEDED
This comment could be made clearer- I'm not sure which default values you are referring to.

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +# TEMMPLATE NAMES
Typo:
```suggestion
# TEMPLATE NAMES
```

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +TEMPLATE_INJESTION_PATH="${TEMPLATE_INJESTION_PATH:-$ASSESSMENT_PATH}"
Not sure if you mean `INGESTION` or `INJECTION` here, but it's a typo either way and should be corrected.

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  sudo mkdir -p "$PCA_DEV_PATH"
Rather than have all of these `sudo` commands in here, why not just require that the script itself be run by a superuser?

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  sudo chown -R vnc:gophish "$EFS_SHARE"
`vnc` and `gophish` should be replaced by variables since these values could be different depending on the environment in which this script is deployed.

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  # TODO: enhance output and error handling)
This TODO comment should include a link to a GitHub issue with details about what needs to be done here.

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +
We typically enable the following options in our shell scripts unless we have a good reason not to:
```
set -o nounset
set -o errexit
set -o pipefail
```

For an example, see [here](https://github.com/cisagov/development-guide/blob/develop/setup-env#L3-L5).

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +    read -rp "Do you need an targets template file generated? (yes/no) " yn
Typo:
```suggestion
    read -rp "Do you need a targets template file generated? (yes/no) " yn
```

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  # Runs the pca-wizard tool to setup a new campaign generate and saves the
The word `generate` doesn't make sense here; this sentence should be cleaned up.

2021-10-08 19:10 UTC, dav3r commented on .gitignore
> +**/lipca-temp
`**/lipca-temp` should be moved from the `## Python ##` section to a new `## Project Specific ##` section (above `## Python ##` for alphabetical order), as we have done [here](https://github.com/cisagov/findings-data-import-lambda/blob/239524883a07063d3d904cf3b4f6902ad9fbae7d/.gitignore#L5-L6).  Even better would be to find a way to get rid of this directory entirely, however if that is not possible/desirable, then it belongs in its own section.

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  # TODO: Determine if we want to keep mix of underscores and hypens in level naming.
This TODO comment should include a link to a GitHub issue with details about what needs to be done here.

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  # TODO: Determine if we want to force complete campaigns and uncomment.
This TODO comment should include a link to a GitHub issue with details about what needs to be done here.

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  # test_post_prompt
This TODO comment should include a link to a GitHub issue with details about what needs to be done here.

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  # Copy templates for injestion
Typo:
```suggestion
  # Copy templates for ingestion
```

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  # data in the lipca-temp dir (generated from create_assessment)
I think this is what is meant here, but please let me know if I'm wrong:
```suggestion
  # data to the lipca-temp dir (generated from create_assessment)
```

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  # Prompts the user to asking if assessment export is needed. Requires
This comment is badly wounded and requires grammatical assistance.

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +        #export_by_id_prompt()
Remove these lines if they are no longer needed.

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  # Prompts the user to test campaign by passing an id with passing
This comment also needs some help.

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  # Run locally pca-gophish-composition/gophish-tools
I don't think this comment makes sense anymore - it should be cleaned up.

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +        # Campaign Cleanup Prompt
Is this comment adding any value here?

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  echo "Beginning Li_PCA Setup Process."
I think `Li-PCA` (as opposed to `Li_PCA`) is our standard now?
```suggestion
  echo "Beginning Li-PCA Setup Process."
```

2021-10-08 19:10 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  echo "Li_PCA Setup Process Complete!!"
Prefer `Li-PCA` to `Li_PCA`:
```suggestion
  echo "Li-PCA Setup Process Complete!!"
```

2021-10-18 21:01 UTC, nickviola commented on .pre-commit-config.yaml
> +    rev: v5.0.8
Addressed in: e49871098e5b027aef309cb06bc86f6551c9b64a

2021-10-18 21:03 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +        # Campaign Cleanup Prompt
Addressed in: f48d5fa727f5229b0690bd6ab9e144477a5e67cc

2021-10-18 21:03 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +  # Run locally pca-gophish-composition/gophish-tools
Addressed in: f48d5fa727f5229b0690bd6ab9e144477a5e67cc

2021-10-18 21:03 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +  # Prompts the user to test campaign by passing an id with passing
Addressed in: f48d5fa727f5229b0690bd6ab9e144477a5e67cc

2021-10-19 17:24 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  # Prompts the user to test campaign by passing an id with passing
@nickviola - Reminder that the person who starts the conversation (me, in this case) should be the one to mark it "resolved".

2021-10-19 20:10 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +# OVERRIDE DEFAULT VALUES WITH ENV VARS AS NEEDED
Added detail to this in 7d95058. If it creates too much confusion, I can modify or simplify it. The goal was flexibility without code changes, but don't want to add too much complexity if it's not useful.

2021-10-19 20:29 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +TEMPLATE_INJESTION_PATH="${TEMPLATE_INJESTION_PATH:-$ASSESSMENT_PATH}"
Updated in 8bb0377

2021-10-19 20:31 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +        #export_by_id_prompt()
Updated in 8bb0377

2021-10-19 20:31 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +  # Prompts the user to asking if assessment export is needed. Requires
Address in: 8bb0377

2021-10-19 20:31 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +  # Runs the pca-wizard tool to setup a new campaign generate and saves the
Address in: 8bb0377

2021-10-19 22:20 UTC, nickviola commented on .gitignore
> +**/lipca-temp
Updated in b3acdb4

2021-10-19 22:24 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +# TEMMPLATE NAMES
Addressed in b1fd983bff530b3e938623cfc929e3b1ff307425. Sorry about not using the suggestion here. I fixed it prior to seeing the suggestion. Thanks though.

2021-10-19 22:29 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +  sudo mkdir -p "$PCA_DEV_PATH"
My intention was to limit sudo usage where possible, but if there is no issue running the script as superuser that can be changed.

2021-10-19 22:42 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +  sudo chown -R vnc:gophish "$EFS_SHARE"
Updated in c9decad

2021-10-19 22:47 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +
Updated in a576de0

2021-10-19 23:08 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +  # TODO: Determine if we want to keep mix of underscores and hypens in level naming.
Updated in fc3a5a1. We are refactoring the setup process and these TODO items are no longer valid. Cleaned them up.

2021-10-19 23:09 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +  # TODO: Determine if we want to force complete campaigns and uncomment.
Updated in fc3a5a1. We are refactoring the setup process and these TODO items are no longer valid. Cleaned them up.

2021-10-19 23:14 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +TEMPLATE_INJESTION_PATH="${TEMPLATE_INJESTION_PATH:-$ASSESSMENT_PATH}"
I don't know how I managed that typo, but thanks for catching it. 😂  Fixed.

2021-10-19 23:16 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +  # TODO: enhance output and error handling)
Updated in fc3a5a1. We are refactoring the setup process and these TODO items are no longer valid. Cleaned them up.

2021-10-19 23:17 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +  # test_post_prompt
Updated in fc3a5a1. We are refactoring the setup process and these TODO items are no longer valid. Cleaned them up. The logic will be re-written, but Incorporating the test prompts in the meantime to allow that option for users.

2021-10-19 23:25 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +  # Prompts the user to test campaign by passing an id with passing
Apologies @dav3r. I realized that I had made that mistake after it was too late. I'll be sure to leave it open going forward. Sorry again and thanks for all your help!

2021-10-19 23:31 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +  # Prompts the user to test campaign by passing an id with passing
I have unresolved the ones I marked as resolved, so hopefully that makes it easier on your end. Sorry for all the emails. 😆 Thanks again!

2021-10-20 15:05 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  # Prompts the user to test campaign by passing an id with passing
The one exception to this rule is when you commit a suggestion made by someone else- in those cases, GitHub automatically resolves the conversation because you accepted their suggestion.

2021-10-20 15:08 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  sudo mkdir -p "$PCA_DEV_PATH"
In this case, if so many parts of the script require `sudo`, then you might as well just run the whole thing with `sudo`, but that decision is up to you.

2021-10-20 15:12 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +# OVERRIDE DEFAULT VALUES WITH ENV VARS AS NEEDED
That explanation works for me.  I have one tiny capitalization change that I will request, but the content looks good to me.

2021-10-20 15:13 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +# The Constants below in ALL_CAPS follow this format: ${ENV_VAR:-default_value}
Remove unnecessary capitalization:
```suggestion
# The constants below in ALL_CAPS follow this format: ${ENV_VAR:-default_value}
```

2021-10-20 21:32 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +  sudo mkdir -p "$PCA_DEV_PATH"
I like your suggestion better. I think it looks cleaner without the sudo repetition. We'll run the script as sudo. Thanks for the input!

Updated in a3d8a31

2021-10-21 13:23 UTC, dav3r commented on gophish-tools/lipca-setup.sh
> +  sudo mkdir -p "$PCA_DEV_PATH"
No problem! 👍

2021-10-21 13:25 UTC, dav3r approved these changes
Looks good to me - thanks for considering my feedback! 🏋️

2021-10-21 13:26 UTC, dav3r commented
@jsf9k and/or @felddy - please review this PR when you can.

2021-10-21 16:03 UTC, jsf9k approved these changes
I made a couple of minor suggestions in the interest of verb tense agreement, but those are nothing that should hold up this PR.

2021-10-21 16:03 UTC, jsf9k commented on gophish-tools/lipca-setup.sh
> +  # directory and open vim to edit the template as needed for modification.
```suggestion
  # directory and opens vim to edit the template as needed for modification.
```

2021-10-21 16:03 UTC, jsf9k commented on gophish-tools/lipca-setup.sh
> +  # directory and open vim to edit the template as needed for modification.
```suggestion
  # directory and opens vim to edit the template as needed for modification.
```

2021-10-21 18:57 UTC, nickviola commented
> I made a couple of minor suggestions in the interest of verb tense agreement, but those are nothing that should hold up this PR.

Thanks for taking a look @jsf9k. I'll go ahead and add these in here as well.

2021-10-21 19:02 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +  # directory and open vim to edit the template as needed for modification.
Fixed in f348d37

2021-10-21 19:02 UTC, nickviola commented on gophish-tools/lipca-setup.sh
> +  # directory and open vim to edit the template as needed for modification.
Fixed in 3eb23c0

2021-10-21 19:40 UTC, nickviola commented
All set to merge on this end as you all get time. Thanks again for the feedback and reviews!

2021-10-21 20:31 UTC, merged