⚠️ CONFLICT! Lineage pull request for: skeleton
cisagov/pca-gophish-composition pull request #8
Opened 2020-05-13 22:16 UTC by felddy

# Lineage Pull Request: CONFLICT #

![DANGER](https://raw.githubusercontent.com/cisagov/action-lineage/develop/src/achtung.gif)

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-docker.git`](https://github.com/cisagov/skeleton-docker.git)

Check the changes in this pull request to ensure they won't cause issues with
your project.

The `lineage/skeleton` branch has **one or more unresolved merge conflicts**
that you must resolve before merging this pull request!

## How to resolve the conflicts ##

1. Clone the `lineage/skeleton` branch locally:

    ```console
    git clone --single-branch --branch lineage/skeleton git@github.com:cisagov/pca-gophish-composition.git
    ```

1. Review each of the following files looking for [conflict-resolution markers](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging#_basic_merge_conflicts):

    ```console
    .bandit.yml
    .github/workflows/build.yml
    .gitignore
    .isort.cfg
    .pre-commit-config.yaml
    CONTRIBUTING.md
    README.md
    docker-compose.yml
    requirements-test.txt
    tests/conftest.py
    tests/container_test.py
    ```

1. Resolve each of the conflicts and `add` your changes to the branch:

    ```console
    git add .bandit.yml .github/workflows/build.yml .gitignore .isort.cfg .pre-commit-config.yaml CONTRIBUTING.md README.md docker-compose.yml requirements-test.txt tests/conftest.py tests/container_test.py 
    ```

1. Once all the changes have been added, `commit` and `push` the changes back to
GitHub:

    ```console
    git commit --message="Resolved Lineage conflicts."
    git push
    ```

1. Wait for all the automated tests to pass.

1. Check the "Everything is cool" checkbox below:

    - [ ] ✌️ The conflicts in this pull request have been resolved.

1. Mark this draft pull request "Ready for review".

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

2020-05-13 22:44 UTC, felddy commented
Jumping Jesus on a pogo stick!

2020-05-14 13:26 UTC, jsf9k requested changes
I think there are at least a few errors/omissions here.

2020-05-14 13:26 UTC, jsf9k commented on Dockerfile
> +RUN wget -O sourcecode.tgz https://github.com/cisagov/skeleton-python-library/archive/v${VERSION}.tar.gz && \
This looks incorrect.  Is this file needed?

2020-05-14 13:26 UTC, jsf9k commented on bump_version.sh
> +#!/usr/bin/env bash
If this file exists then don't we need to pull in `semver`, perhaps via `requirements-dev.txt`?  Usually we put `ipython` in `requirements-dev.txt` as well.  I'm not sure why that file got removed from this PR.

2020-05-14 13:51 UTC, felddy commented on Dockerfile
> +RUN wget -O sourcecode.tgz https://github.com/cisagov/skeleton-python-library/archive/v${VERSION}.tar.gz && \
Egads!  You are correct!  I missed the entire clean file additions that came in.

2020-05-14 13:53 UTC, felddy commented on .github/workflows/build.yml
> +  IMAGE_NAME: cisagov/example
This is wrong.

2020-05-14 13:53 UTC, felddy commented on .github/workflows/release.yml
> +  IMAGE_NAME: cisagov/example
WRONG!

2020-05-14 13:54 UTC, felddy commented on .github/workflows/release.yml
> +  IMAGE_NAME: cisagov/example
![SlsSmSr](https://user-images.githubusercontent.com/3229435/81943082-eff48a00-95c8-11ea-8e6d-c0711f911335.png)

2020-05-14 13:57 UTC, felddy commented on .github/workflows/release.yml
> +  IMAGE_NAME: cisagov/example
I was going to change this back to "Draft" status, but the button isn't working.  Maybe because of the "changes requested" state.  In any case, I apologize for this crap ass merge job I did.  I'll clean this up once I get off dad-doody.

2020-05-14 14:04 UTC, jsf9k commented on .github/workflows/release.yml
> +  IMAGE_NAME: cisagov/example
No worries.  This very thang caught me slippin' a few days ago in another repo when I switched from `skeleton-packer-cool` to `skeleton-packer` as the skeleton.

Doing `git status` and `git diff` right after the `git merge` and checking that all the cleanly merged files make sense is key.  `git` handles merges like a champ, but it doesn't always do what you want.  It is good to be reminded of these things from time to time.

2020-05-14 15:57 UTC, felddy commented
Ok.  Let's try this again.  A lot of the pain was caused by a mismatch in the lineage.  This project is not a Docker container.  It is more akin to a Python library.  Once I made that change the pieces fell into place better. 

Again... I apologize for the previous state of the merge.

2020-05-14 17:16 UTC, jsf9k approved these changes
I _think_ this merge is OK now.

2020-05-14 17:22 UTC, dav3r approved these changes
Everything looks good, except for the version file stuff I mentioned below.
👍

2020-05-14 17:22 UTC, dav3r commented on src/version.txt
> +__version__ = "0.0.1"
Shouldn't we use `src/gophish_init/_version.py` as the version file for this repo?

2020-05-14 17:22 UTC, dav3r commented on bump_version.sh
> +VERSION_FILE=src/version.txt
Shouldn't we use `src/gophish_init/_version.py` as the version file for this repo?

2020-05-14 17:41 UTC, merged